export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_CHEAPFLIGHTS_SUCCESS = 'LOAD_CHEAPFLIGHTS_SUCCESS';
export const CREATE_CHEAPFLIGHT_SUCCESS = 'CREATE_CHEAPFLIGHT_SUCCESS';
export const UPDATE_CHEAPFLIGHT_SUCCESS = 'UPDATE_CHEAPFLIGHT_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';

